### ISSUE TITLE
Astar Wiki CS 板块 Logo 设计

### ISSUE THREAD

**Issue by AlanJinqs** [SCIE-PRO-Open-Source/Logos#1]

**Comment by ACCIVATOR** [comment]
<img width="512" alt="AstarComputerScience" src="https://user-images.githubusercontent.com/44864233/64674660-e2b85600-d4a3-11e9-957f-99f3983690b9.png">

**Comment by ACCIVATOR** [comment]
Somebody help me upload this into the repository
